export const weightDescription = {
  '100': 'Thin',
  '200': 'Extra Light',
  '300': 'Light',
  '400': 'Normal',
  '500': 'Medium',
  '600': 'Semi Bold',
  '700': 'Bold',
  '800': 'Extra Bold',
  '900': 'Black',
  '950': 'Extra Black',
  '100i': 'Italic Thin',
  '200i': 'Italic Extra Light',
  '300i': 'Italic Light',
  '400i': 'Italic Normal',
  '500i': 'Italic Medium',
  '600i': 'Italic Semi Bold',
  '700i': 'Italic Bold',
  '800i': 'Italic Extra Bold',
  '900i': 'Italic Black',
  '950i': 'Italic Extra Black',
}

export const characterSetDescription = {
  'cyrillic-ext': 'Cyrillic Extended',
  cyrillic: 'Russian, Ukrainian, Belarusian, Bulgarian...',
  'greek-ext': 'Polytonic Greek Extended',
  greek: 'Greek, Coptic',
  vietnamese: 'Vietnamese Extended',
  'latin-ext': 'Afrikaans, Catalan, Croatian, Czech...',
  latin: 'English, French, German, Spanish, Vietnamese...',
}
